baseurl = "https://old.dddmelbourne.com"
DefaultContentLanguage = "en"
title = "DDD Melbourne"
metaDataFormat = "yaml"
googleAnalytics = "UA-99087610-1"

[Params]
  subtitle = "DDD Melbourne is an inclusive non-profit conference for the Melbourne software community. Our goal is to create an approachable event that appeals to the whole community, especially people who usually don’t have the opportunity to attend, or speak at, conferences."
  favicon = "images/favicon.ico"
  dateFormat = "Mon Jan 2, 2006"
  showDddByNight = true
  image = "https://old.dddmelbourne.com/images/strip/1-talk.jpg"

[Author]
  name = "DDD Melbourne"
  email = "dddmelbourne@gmail.com"
  github = "OpenDDD"
  twitter = "dddmelb"
  instagram = "dddmelb"
  flickr = "photos/135717775@N07/"

[[menu.main]]
    name = "Blog"
    url = "https://blog.dddmelbourne.com/"
    weight = 7
